<?php

namespace Database\Copy\OpenWeather;

// Данные таблицы open_weather.weather
class WeatherData
{
    public function __invoke(): array
    {
        return [
            (object) [
                'id' => 1,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 22.91,
                'main_feels_like' => 22.46,
                'main_pressure' => 1007,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 3.57,
                'wind_deg' => 344,
                'clouds_all' => 100,
                'created_at' => '2023-07-30 13:03:37.896905+00',
            ],
            (object) [
                'id' => 2,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 22.61,
                'main_feels_like' => 22.7,
                'main_pressure' => 1001,
                'main_humidity' => 68,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 300,
                'clouds_all' => 75,
                'created_at' => '2023-07-30 13:05:02.678235+00',
            ],
            (object) [
                'id' => 3,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 22.61,
                'main_feels_like' => 22.7,
                'main_pressure' => 1001,
                'main_humidity' => 68,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 300,
                'clouds_all' => 75,
                'created_at' => '2023-07-30 13:06:20.259695+00',
            ],
            (object) [
                'id' => 4,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 22.91,
                'main_feels_like' => 22.46,
                'main_pressure' => 1007,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 3.57,
                'wind_deg' => 344,
                'clouds_all' => 100,
                'created_at' => '2023-07-30 13:06:20.543655+00',
            ],
            (object) [
                'id' => 5,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 20.61,
                'main_feels_like' => 21.02,
                'main_pressure' => 1006,
                'main_humidity' => 88,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 40,
                'clouds_all' => 75,
                'created_at' => '2023-07-31 12:19:13.804243+00',
            ],
            (object) [
                'id' => 6,
                'city_id' => 4,
                'weather_description' => 'переменная облачность',
                'main_temp' => 24.66,
                'main_feels_like' => 24.25,
                'main_pressure' => 1008,
                'main_humidity' => 41,
                'visibility' => 10000,
                'wind_speed' => 3.25,
                'wind_deg' => 262,
                'clouds_all' => 37,
                'created_at' => '2023-07-31 12:19:14.288343+00',
            ],
            (object) [
                'id' => 7,
                'city_id' => 6,
                'weather_description' => 'переменная облачность',
                'main_temp' => 26.61,
                'main_feels_like' => 26.61,
                'main_pressure' => 1007,
                'main_humidity' => 44,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 330,
                'clouds_all' => 40,
                'created_at' => '2023-07-31 13:11:18.468877+00',
            ],
            (object) [
                'id' => 8,
                'city_id' => 2,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 20.61,
                'main_feels_like' => 21.02,
                'main_pressure' => 1006,
                'main_humidity' => 88,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 40,
                'clouds_all' => 75,
                'created_at' => '2023-07-31 13:11:48.606743+00',
            ],
            (object) [
                'id' => 9,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 24.61,
                'main_feels_like' => 24.61,
                'main_pressure' => 1007,
                'main_humidity' => 57,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 10,
                'clouds_all' => 0,
                'created_at' => '2023-08-05 13:16:36.944185+00',
            ],
            (object) [
                'id' => 10,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 28.78,
                'main_feels_like' => 28.15,
                'main_pressure' => 1018,
                'main_humidity' => 37,
                'visibility' => 10000,
                'wind_speed' => 2.62,
                'wind_deg' => 246,
                'clouds_all' => 7,
                'created_at' => '2023-08-05 13:16:37.308118+00',
            ],
            (object) [
                'id' => 11,
                'city_id' => 6,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 23.83,
                'main_feels_like' => 24.07,
                'main_pressure' => 1008,
                'main_humidity' => 69,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 350,
                'clouds_all' => 40,
                'created_at' => '2023-08-05 13:16:37.588816+00',
            ],
            (object) [
                'id' => 12,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 22.47,
                'main_feels_like' => 22.03,
                'main_pressure' => 996,
                'main_humidity' => 48,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 40,
                'clouds_all' => 0,
                'created_at' => '2023-08-05 13:16:37.903778+00',
            ],
            (object) [
                'id' => 13,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 17.61,
                'main_feels_like' => 16.97,
                'main_pressure' => 1006,
                'main_humidity' => 59,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 360,
                'clouds_all' => 0,
                'created_at' => '2023-08-06 15:12:50.028319+00',
            ],
            (object) [
                'id' => 14,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 30.22,
                'main_feels_like' => 30.47,
                'main_pressure' => 1016,
                'main_humidity' => 44,
                'visibility' => 10000,
                'wind_speed' => 4.31,
                'wind_deg' => 139,
                'clouds_all' => 0,
                'created_at' => '2023-08-06 15:12:50.440017+00',
            ],
            (object) [
                'id' => 15,
                'city_id' => 6,
                'weather_description' => 'ясно',
                'main_temp' => 22.72,
                'main_feels_like' => 22.25,
                'main_pressure' => 1007,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 60,
                'clouds_all' => 0,
                'created_at' => '2023-08-06 15:12:50.686346+00',
            ],
            (object) [
                'id' => 16,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 16.6,
                'main_feels_like' => 16.35,
                'main_pressure' => 994,
                'main_humidity' => 78,
                'visibility' => 10000,
                'wind_speed' => 0,
                'wind_deg' => 0,
                'clouds_all' => 0,
                'created_at' => '2023-08-06 15:12:50.938524+00',
            ],
            (object) [
                'id' => 17,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 19.61,
                'main_feels_like' => 19.19,
                'main_pressure' => 1004,
                'main_humidity' => 60,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 350,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 04:03:17.489902+00',
            ],
            (object) [
                'id' => 18,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 21.71,
                'main_feels_like' => 21.74,
                'main_pressure' => 1016,
                'main_humidity' => 69,
                'visibility' => 10000,
                'wind_speed' => 4.57,
                'wind_deg' => 120,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 04:03:18.021727+00',
            ],
            (object) [
                'id' => 19,
                'city_id' => 6,
                'weather_description' => 'ясно',
                'main_temp' => 21.61,
                'main_feels_like' => 21.11,
                'main_pressure' => 1008,
                'main_humidity' => 49,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 30,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 04:03:18.254946+00',
            ],
            (object) [
                'id' => 20,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 20.13,
                'main_feels_like' => 20.03,
                'main_pressure' => 989,
                'main_humidity' => 70,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 250,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 04:03:18.49281+00',
            ],
            (object) [
                'id' => 21,
                'city_id' => 2,
                'weather_description' => 'переменная облачность',
                'main_temp' => 23.61,
                'main_feels_like' => 22.94,
                'main_pressure' => 1003,
                'main_humidity' => 35,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 0,
                'clouds_all' => 40,
                'created_at' => '2023-08-07 09:38:22.119223+00',
            ],
            (object) [
                'id' => 22,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 28.54,
                'main_feels_like' => 28,
                'main_pressure' => 1013,
                'main_humidity' => 38,
                'visibility' => 10000,
                'wind_speed' => 6.94,
                'wind_deg' => 122,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 09:38:22.575593+00',
            ],
            (object) [
                'id' => 23,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 25.5,
                'main_feels_like' => 24.99,
                'main_pressure' => 1006,
                'main_humidity' => 34,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 300,
                'clouds_all' => 75,
                'created_at' => '2023-08-07 09:38:22.929464+00',
            ],
            (object) [
                'id' => 24,
                'city_id' => 7,
                'weather_description' => 'небольшая облачность',
                'main_temp' => 23.92,
                'main_feels_like' => 23.67,
                'main_pressure' => 988,
                'main_humidity' => 50,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 330,
                'clouds_all' => 20,
                'created_at' => '2023-08-07 09:38:23.209906+00',
            ],
            (object) [
                'id' => 25,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 21.61,
                'main_feels_like' => 21.21,
                'main_pressure' => 1003,
                'main_humidity' => 53,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 280,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 14:08:04.204122+00',
            ],
            (object) [
                'id' => 26,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 29.5,
                'main_feels_like' => 29.03,
                'main_pressure' => 1011,
                'main_humidity' => 39,
                'visibility' => 10000,
                'wind_speed' => 6.68,
                'wind_deg' => 128,
                'clouds_all' => 0,
                'created_at' => '2023-08-07 14:08:05.54351+00',
            ],
            (object) [
                'id' => 27,
                'city_id' => 6,
                'weather_description' => 'переменная облачность',
                'main_temp' => 24.94,
                'main_feels_like' => 24.43,
                'main_pressure' => 1005,
                'main_humidity' => 36,
                'visibility' => 10000,
                'wind_speed' => 4.02,
                'wind_deg' => 50,
                'clouds_all' => 40,
                'created_at' => '2023-08-07 14:08:05.861097+00',
            ],
            (object) [
                'id' => 28,
                'city_id' => 7,
                'weather_description' => 'дождь',
                'main_temp' => 19.25,
                'main_feels_like' => 19.32,
                'main_pressure' => 989,
                'main_humidity' => 80,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 170,
                'clouds_all' => 20,
                'created_at' => '2023-08-07 14:08:06.237252+00',
            ],
            (object) [
                'id' => 29,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 25.61,
                'main_feels_like' => 25.38,
                'main_pressure' => 1004,
                'main_humidity' => 44,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 10,
                'clouds_all' => 0,
                'created_at' => '2023-08-08 11:43:36.364025+00',
            ],
            (object) [
                'id' => 30,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 25.03,
                'main_feels_like' => 24.87,
                'main_pressure' => 1009,
                'main_humidity' => 49,
                'visibility' => 10000,
                'wind_speed' => 2.16,
                'wind_deg' => 182,
                'clouds_all' => 59,
                'created_at' => '2023-08-08 11:43:36.900481+00',
            ],
            (object) [
                'id' => 31,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 27.72,
                'main_feels_like' => 27.09,
                'main_pressure' => 1005,
                'main_humidity' => 34,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 310,
                'clouds_all' => 75,
                'created_at' => '2023-08-08 11:43:37.150169+00',
            ],
            (object) [
                'id' => 32,
                'city_id' => 7,
                'weather_description' => 'переменная облачность',
                'main_temp' => 23.15,
                'main_feels_like' => 23.04,
                'main_pressure' => 991,
                'main_humidity' => 58,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 330,
                'clouds_all' => 40,
                'created_at' => '2023-08-08 11:43:37.385694+00',
            ],
            (object) [
                'id' => 33,
                'city_id' => 2,
                'weather_description' => 'дымка',
                'main_temp' => 21.61,
                'main_feels_like' => 21.5,
                'main_pressure' => 1008,
                'main_humidity' => 64,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 40,
                'clouds_all' => 100,
                'created_at' => '2023-08-09 04:11:40.587743+00',
            ],
            (object) [
                'id' => 34,
                'city_id' => 4,
                'weather_description' => 'небольшая облачность',
                'main_temp' => 17.41,
                'main_feels_like' => 17.24,
                'main_pressure' => 1012,
                'main_humidity' => 78,
                'visibility' => 10000,
                'wind_speed' => 3.22,
                'wind_deg' => 337,
                'clouds_all' => 21,
                'created_at' => '2023-08-09 04:11:40.904195+00',
            ],
            (object) [
                'id' => 35,
                'city_id' => 6,
                'weather_description' => 'ясно',
                'main_temp' => 23.83,
                'main_feels_like' => 23.57,
                'main_pressure' => 1010,
                'main_humidity' => 50,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 10,
                'clouds_all' => 0,
                'created_at' => '2023-08-09 04:11:41.135011+00',
            ],
            (object) [
                'id' => 36,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 20.9,
                'main_feels_like' => 20.74,
                'main_pressure' => 994,
                'main_humidity' => 65,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 0,
                'clouds_all' => 0,
                'created_at' => '2023-08-09 04:11:41.384101+00',
            ],
            (object) [
                'id' => 37,
                'city_id' => 2,
                'weather_description' => 'переменная облачность',
                'main_temp' => 18.61,
                'main_feels_like' => 18.3,
                'main_pressure' => 1009,
                'main_humidity' => 68,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 360,
                'clouds_all' => 40,
                'created_at' => '2023-08-09 13:43:28.305008+00',
            ],
            (object) [
                'id' => 38,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 24.23,
                'main_feels_like' => 24.46,
                'main_pressure' => 1013,
                'main_humidity' => 67,
                'visibility' => 10000,
                'wind_speed' => 3.86,
                'wind_deg' => 303,
                'clouds_all' => 74,
                'created_at' => '2023-08-09 13:43:28.806723+00',
            ],
            (object) [
                'id' => 39,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 25.5,
                'main_feels_like' => 25.12,
                'main_pressure' => 1010,
                'main_humidity' => 39,
                'visibility' => 10000,
                'wind_speed' => 4.02,
                'wind_deg' => 10,
                'clouds_all' => 75,
                'created_at' => '2023-08-09 13:43:29.086221+00',
            ],
            (object) [
                'id' => 40,
                'city_id' => 7,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 20.36,
                'main_feels_like' => 20.15,
                'main_pressure' => 995,
                'main_humidity' => 65,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 240,
                'clouds_all' => 0,
                'created_at' => '2023-08-09 13:43:29.398925+00',
            ],
            (object) [
                'id' => 41,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 18.61,
                'main_feels_like' => 17.96,
                'main_pressure' => 1005,
                'main_humidity' => 55,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 330,
                'clouds_all' => 75,
                'created_at' => '2023-08-11 12:42:10.495495+00',
            ],
            (object) [
                'id' => 42,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 22.91,
                'main_feels_like' => 23.11,
                'main_pressure' => 1021,
                'main_humidity' => 71,
                'visibility' => 10000,
                'wind_speed' => 2.58,
                'wind_deg' => 119,
                'clouds_all' => 100,
                'created_at' => '2023-08-11 12:42:10.862962+00',
            ],
            (object) [
                'id' => 43,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 14.94,
                'main_feels_like' => 14.76,
                'main_pressure' => 1011,
                'main_humidity' => 87,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 350,
                'clouds_all' => 75,
                'created_at' => '2023-08-11 12:42:11.075885+00',
            ],
            (object) [
                'id' => 44,
                'city_id' => 7,
                'weather_description' => 'переменная облачность',
                'main_temp' => 19.61,
                'main_feels_like' => 19.22,
                'main_pressure' => 991,
                'main_humidity' => 61,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 240,
                'clouds_all' => 40,
                'created_at' => '2023-08-11 12:42:11.29818+00',
            ],
            (object) [
                'id' => 45,
                'city_id' => 2,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 13.61,
                'main_feels_like' => 13.48,
                'main_pressure' => 1005,
                'main_humidity' => 94,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 30,
                'clouds_all' => 100,
                'created_at' => '2023-08-12 10:33:40.023295+00',
            ],
            (object) [
                'id' => 46,
                'city_id' => 4,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 20.79,
                'main_feels_like' => 20.49,
                'main_pressure' => 1016,
                'main_humidity' => 60,
                'visibility' => 10000,
                'wind_speed' => 5.74,
                'wind_deg' => 88,
                'clouds_all' => 100,
                'created_at' => '2023-08-12 10:33:40.597743+00',
            ],
            (object) [
                'id' => 47,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 14.94,
                'main_feels_like' => 14,
                'main_pressure' => 1012,
                'main_humidity' => 58,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 360,
                'clouds_all' => 75,
                'created_at' => '2023-08-12 10:33:40.947413+00',
            ],
            (object) [
                'id' => 48,
                'city_id' => 7,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 14.58,
                'main_feels_like' => 14.63,
                'main_pressure' => 990,
                'main_humidity' => 97,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 0,
                'clouds_all' => 75,
                'created_at' => '2023-08-12 10:33:41.306204+00',
            ],
            (object) [
                'id' => 49,
                'city_id' => 2,
                'weather_description' => 'пасмурно',
                'main_temp' => 12.61,
                'main_feels_like' => 11.91,
                'main_pressure' => 1009,
                'main_humidity' => 76,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 330,
                'clouds_all' => 100,
                'created_at' => '2023-08-13 12:54:42.512766+00',
            ],
            (object) [
                'id' => 50,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 19.36,
                'main_feels_like' => 19.52,
                'main_pressure' => 1014,
                'main_humidity' => 83,
                'visibility' => 10000,
                'wind_speed' => 4.8,
                'wind_deg' => 176,
                'clouds_all' => 100,
                'created_at' => '2023-08-13 12:54:42.947603+00',
            ],
            (object) [
                'id' => 51,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 12.94,
                'main_feels_like' => 12.14,
                'main_pressure' => 1015,
                'main_humidity' => 71,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 350,
                'clouds_all' => 75,
                'created_at' => '2023-08-13 12:54:43.230775+00',
            ],
            (object) [
                'id' => 52,
                'city_id' => 7,
                'weather_description' => 'небольшая облачность',
                'main_temp' => 13.38,
                'main_feels_like' => 13.02,
                'main_pressure' => 996,
                'main_humidity' => 86,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 290,
                'clouds_all' => 20,
                'created_at' => '2023-08-13 12:54:43.586388+00',
            ],
            (object) [
                'id' => 53,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 13.61,
                'main_feels_like' => 13.17,
                'main_pressure' => 1014,
                'main_humidity' => 82,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 200,
                'clouds_all' => 75,
                'created_at' => '2023-08-14 12:52:04.211706+00',
            ],
            (object) [
                'id' => 54,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 22.12,
                'main_feels_like' => 22.24,
                'main_pressure' => 1017,
                'main_humidity' => 71,
                'visibility' => 10000,
                'wind_speed' => 5.62,
                'wind_deg' => 288,
                'clouds_all' => 81,
                'created_at' => '2023-08-14 12:52:04.614042+00',
            ],
            (object) [
                'id' => 55,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 17.94,
                'main_feels_like' => 17.23,
                'main_pressure' => 1013,
                'main_humidity' => 55,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 310,
                'clouds_all' => 75,
                'created_at' => '2023-08-14 12:52:04.935614+00',
            ],
            (object) [
                'id' => 56,
                'city_id' => 7,
                'weather_description' => 'дождь',
                'main_temp' => 13.74,
                'main_feels_like' => 13.62,
                'main_pressure' => 1000,
                'main_humidity' => 94,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 270,
                'clouds_all' => 40,
                'created_at' => '2023-08-14 12:52:05.169739+00',
            ],
            (object) [
                'id' => 57,
                'city_id' => 2,
                'weather_description' => 'переменная облачность',
                'main_temp' => 18.61,
                'main_feels_like' => 18.07,
                'main_pressure' => 1015,
                'main_humidity' => 59,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 290,
                'clouds_all' => 40,
                'created_at' => '2023-08-15 12:27:25.057814+00',
            ],
            (object) [
                'id' => 58,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 25.62,
                'main_feels_like' => 25.39,
                'main_pressure' => 1020,
                'main_humidity' => 44,
                'visibility' => 10000,
                'wind_speed' => 3.95,
                'wind_deg' => 311,
                'clouds_all' => 84,
                'created_at' => '2023-08-15 12:27:25.545463+00',
            ],
            (object) [
                'id' => 59,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 17.72,
                'main_feels_like' => 17.09,
                'main_pressure' => 1015,
                'main_humidity' => 59,
                'visibility' => 10000,
                'wind_speed' => 4.02,
                'wind_deg' => 30,
                'clouds_all' => 75,
                'created_at' => '2023-08-15 12:27:25.861751+00',
            ],
            (object) [
                'id' => 60,
                'city_id' => 7,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 15.59,
                'main_feels_like' => 15.48,
                'main_pressure' => 1002,
                'main_humidity' => 87,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 170,
                'clouds_all' => 20,
                'created_at' => '2023-08-15 12:27:26.232455+00',
            ],
            (object) [
                'id' => 61,
                'city_id' => 2,
                'weather_description' => 'пасмурно',
                'main_temp' => 13.61,
                'main_feels_like' => 13.48,
                'main_pressure' => 1009,
                'main_humidity' => 94,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 250,
                'clouds_all' => 100,
                'created_at' => '2023-08-16 12:55:01.445286+00',
            ],
            (object) [
                'id' => 62,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 26.1,
                'main_feels_like' => 26.1,
                'main_pressure' => 1023,
                'main_humidity' => 38,
                'visibility' => 10000,
                'wind_speed' => 3.72,
                'wind_deg' => 346,
                'clouds_all' => 0,
                'created_at' => '2023-08-16 12:55:02.203884+00',
            ],
            (object) [
                'id' => 63,
                'city_id' => 6,
                'weather_description' => 'переменная облачность',
                'main_temp' => 22.72,
                'main_feels_like' => 22.33,
                'main_pressure' => 1015,
                'main_humidity' => 49,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 330,
                'clouds_all' => 40,
                'created_at' => '2023-08-16 12:55:02.501293+00',
            ],
            (object) [
                'id' => 64,
                'city_id' => 7,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 12.98,
                'main_feels_like' => 12.92,
                'main_pressure' => 993,
                'main_humidity' => 99,
                'visibility' => 2700,
                'wind_speed' => 6,
                'wind_deg' => 210,
                'clouds_all' => 75,
                'created_at' => '2023-08-16 12:55:02.888288+00',
            ],
            (object) [
                'id' => 65,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 14.61,
                'main_feels_like' => 14.01,
                'main_pressure' => 1014,
                'main_humidity' => 72,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 350,
                'clouds_all' => 0,
                'created_at' => '2023-08-17 13:01:36.549284+00',
            ],
            (object) [
                'id' => 66,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 27.95,
                'main_feels_like' => 27.26,
                'main_pressure' => 1022,
                'main_humidity' => 34,
                'visibility' => 10000,
                'wind_speed' => 2.04,
                'wind_deg' => 10,
                'clouds_all' => 75,
                'created_at' => '2023-08-17 13:01:37.086138+00',
            ],
            (object) [
                'id' => 67,
                'city_id' => 6,
                'weather_description' => 'ясно',
                'main_temp' => 21.61,
                'main_feels_like' => 21.03,
                'main_pressure' => 1017,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 20,
                'clouds_all' => 0,
                'created_at' => '2023-08-17 13:01:37.431404+00',
            ],
            (object) [
                'id' => 68,
                'city_id' => 7,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 12.78,
                'main_feels_like' => 12.62,
                'main_pressure' => 1000,
                'main_humidity' => 96,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 300,
                'clouds_all' => 75,
                'created_at' => '2023-08-17 13:01:37.839462+00',
            ],
            (object) [
                'id' => 69,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 18.61,
                'main_feels_like' => 17.78,
                'main_pressure' => 1014,
                'main_humidity' => 48,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 290,
                'clouds_all' => 0,
                'created_at' => '2023-08-18 12:58:13.724176+00',
            ],
            (object) [
                'id' => 70,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 24.29,
                'main_feels_like' => 24,
                'main_pressure' => 1023,
                'main_humidity' => 47,
                'visibility' => 10000,
                'wind_speed' => 2.69,
                'wind_deg' => 5,
                'clouds_all' => 81,
                'created_at' => '2023-08-18 12:58:14.118505+00',
            ],
            (object) [
                'id' => 71,
                'city_id' => 6,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 23.83,
                'main_feels_like' => 23.47,
                'main_pressure' => 1016,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 4.02,
                'wind_deg' => 300,
                'clouds_all' => 75,
                'created_at' => '2023-08-18 12:58:14.608265+00',
            ],
            (object) [
                'id' => 72,
                'city_id' => 7,
                'weather_description' => 'переменная облачность',
                'main_temp' => 16.73,
                'main_feels_like' => 16.26,
                'main_pressure' => 1000,
                'main_humidity' => 69,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 220,
                'clouds_all' => 40,
                'created_at' => '2023-08-18 12:58:14.857266+00',
            ],
            (object) [
                'id' => 73,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 19.61,
                'main_feels_like' => 19.53,
                'main_pressure' => 1010,
                'main_humidity' => 73,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 230,
                'clouds_all' => 75,
                'created_at' => '2023-08-19 10:06:53.057517+00',
            ],
            (object) [
                'id' => 74,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 26.25,
                'main_feels_like' => 26.25,
                'main_pressure' => 1024,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 1.54,
                'wind_deg' => 57,
                'clouds_all' => 64,
                'created_at' => '2023-08-19 10:06:53.333424+00',
            ],
            (object) [
                'id' => 75,
                'city_id' => 6,
                'weather_description' => 'переменная облачность',
                'main_temp' => 26.94,
                'main_feels_like' => 27.36,
                'main_pressure' => 1009,
                'main_humidity' => 50,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 220,
                'clouds_all' => 40,
                'created_at' => '2023-08-19 10:06:53.572912+00',
            ],
            (object) [
                'id' => 76,
                'city_id' => 7,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 19.74,
                'main_feels_like' => 19.57,
                'main_pressure' => 999,
                'main_humidity' => 69,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 110,
                'clouds_all' => 40,
                'created_at' => '2023-08-19 10:06:53.822417+00',
            ],
            (object) [
                'id' => 77,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 23.61,
                'main_feels_like' => 23.51,
                'main_pressure' => 1009,
                'main_humidity' => 57,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 280,
                'clouds_all' => 75,
                'created_at' => '2023-08-20 10:26:58.292858+00',
            ],
            (object) [
                'id' => 78,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 25.52,
                'main_feels_like' => 25.41,
                'main_pressure' => 1017,
                'main_humidity' => 49,
                'visibility' => 10000,
                'wind_speed' => 4.08,
                'wind_deg' => 271,
                'clouds_all' => 99,
                'created_at' => '2023-08-20 10:26:58.59251+00',
            ],
            (object) [
                'id' => 79,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 19.94,
                'main_feels_like' => 19.27,
                'main_pressure' => 1015,
                'main_humidity' => 49,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 340,
                'clouds_all' => 75,
                'created_at' => '2023-08-20 10:26:58.834989+00',
            ],
            (object) [
                'id' => 80,
                'city_id' => 7,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 18.82,
                'main_feels_like' => 19.08,
                'main_pressure' => 996,
                'main_humidity' => 89,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 140,
                'clouds_all' => 75,
                'created_at' => '2023-08-20 10:26:59.063228+00',
            ],
            (object) [
                'id' => 81,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 16.61,
                'main_feels_like' => 16.34,
                'main_pressure' => 1015,
                'main_humidity' => 77,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 330,
                'clouds_all' => 75,
                'created_at' => '2023-08-21 13:58:34.536518+00',
            ],
            (object) [
                'id' => 82,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 21.58,
                'main_feels_like' => 20.73,
                'main_pressure' => 1015,
                'main_humidity' => 36,
                'visibility' => 10000,
                'wind_speed' => 2.35,
                'wind_deg' => 10,
                'clouds_all' => 3,
                'created_at' => '2023-08-21 13:58:35.016026+00',
            ],
            (object) [
                'id' => 83,
                'city_id' => 6,
                'weather_description' => 'ясно',
                'main_temp' => 21.94,
                'main_feels_like' => 21.1,
                'main_pressure' => 1012,
                'main_humidity' => 35,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 140,
                'clouds_all' => 0,
                'created_at' => '2023-08-21 13:58:35.250886+00',
            ],
            (object) [
                'id' => 84,
                'city_id' => 7,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 15.63,
                'main_feels_like' => 15.6,
                'main_pressure' => 1001,
                'main_humidity' => 90,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 290,
                'clouds_all' => 75,
                'created_at' => '2023-08-21 13:58:35.512548+00',
            ],
            (object) [
                'id' => 85,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 21.61,
                'main_feels_like' => 21.11,
                'main_pressure' => 1009,
                'main_humidity' => 49,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 170,
                'clouds_all' => 0,
                'created_at' => '2023-08-22 12:40:52.339365+00',
            ],
            (object) [
                'id' => 86,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 18.21,
                'main_feels_like' => 17.71,
                'main_pressure' => 1010,
                'main_humidity' => 62,
                'visibility' => 10000,
                'wind_speed' => 3.41,
                'wind_deg' => 275,
                'clouds_all' => 100,
                'created_at' => '2023-08-22 12:40:52.729993+00',
            ],
            (object) [
                'id' => 87,
                'city_id' => 6,
                'weather_description' => 'переменная облачность',
                'main_temp' => 22.72,
                'main_feels_like' => 22.43,
                'main_pressure' => 1006,
                'main_humidity' => 53,
                'visibility' => 10000,
                'wind_speed' => 7.15,
                'wind_deg' => 310,
                'clouds_all' => 40,
                'created_at' => '2023-08-22 12:40:52.966166+00',
            ],
            (object) [
                'id' => 88,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 20.12,
                'main_feels_like' => 19.88,
                'main_pressure' => 997,
                'main_humidity' => 65,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 160,
                'clouds_all' => 0,
                'created_at' => '2023-08-22 12:40:53.284502+00',
            ],
            (object) [
                'id' => 89,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 23.61,
                'main_feels_like' => 23.15,
                'main_pressure' => 1009,
                'main_humidity' => 43,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 290,
                'clouds_all' => 0,
                'created_at' => '2023-08-23 09:59:12.260036+00',
            ],
            (object) [
                'id' => 90,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 17.96,
                'main_feels_like' => 17.33,
                'main_pressure' => 1009,
                'main_humidity' => 58,
                'visibility' => 10000,
                'wind_speed' => 1.81,
                'wind_deg' => 303,
                'clouds_all' => 99,
                'created_at' => '2023-08-23 09:59:12.616728+00',
            ],
            (object) [
                'id' => 91,
                'city_id' => 6,
                'weather_description' => 'переменная облачность',
                'main_temp' => 24.94,
                'main_feels_like' => 24.87,
                'main_pressure' => 1001,
                'main_humidity' => 53,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 150,
                'clouds_all' => 40,
                'created_at' => '2023-08-23 09:59:12.871848+00',
            ],
            (object) [
                'id' => 92,
                'city_id' => 7,
                'weather_description' => 'переменная облачность',
                'main_temp' => 22.58,
                'main_feels_like' => 22.72,
                'main_pressure' => 995,
                'main_humidity' => 70,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 290,
                'clouds_all' => 40,
                'created_at' => '2023-08-23 09:59:13.074234+00',
            ],
            (object) [
                'id' => 93,
                'city_id' => 2,
                'weather_description' => 'переменная облачность',
                'main_temp' => 21.61,
                'main_feels_like' => 21.29,
                'main_pressure' => 1002,
                'main_humidity' => 56,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 340,
                'clouds_all' => 40,
                'created_at' => '2023-08-24 13:24:48.127746+00',
            ],
            (object) [
                'id' => 94,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 15.62,
                'main_feels_like' => 14.86,
                'main_pressure' => 1012,
                'main_humidity' => 62,
                'visibility' => 10000,
                'wind_speed' => 3.38,
                'wind_deg' => 20,
                'clouds_all' => 87,
                'created_at' => '2023-08-24 13:24:48.887813+00',
            ],
            (object) [
                'id' => 95,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 14.94,
                'main_feels_like' => 14.37,
                'main_pressure' => 1003,
                'main_humidity' => 72,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 360,
                'clouds_all' => 75,
                'created_at' => '2023-08-24 13:24:49.1896+00',
            ],
            (object) [
                'id' => 96,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 26.91,
                'main_feels_like' => 28.18,
                'main_pressure' => 989,
                'main_humidity' => 63,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 140,
                'clouds_all' => 0,
                'created_at' => '2023-08-24 13:24:49.439041+00',
            ],
            (object) [
                'id' => 97,
                'city_id' => 2,
                'weather_description' => 'гроза с сильным дождём',
                'main_temp' => 17.61,
                'main_feels_like' => 18.04,
                'main_pressure' => 997,
                'main_humidity' => 100,
                'visibility' => 1800,
                'wind_speed' => 15,
                'wind_deg' => 300,
                'clouds_all' => 100,
                'created_at' => '2023-08-25 10:51:33.936121+00',
            ],
            (object) [
                'id' => 98,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 17.99,
                'main_feels_like' => 17.02,
                'main_pressure' => 1016,
                'main_humidity' => 45,
                'visibility' => 10000,
                'wind_speed' => 1.36,
                'wind_deg' => 324,
                'clouds_all' => 100,
                'created_at' => '2023-08-25 10:51:34.369159+00',
            ],
            (object) [
                'id' => 99,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 18.83,
                'main_feels_like' => 17.79,
                'main_pressure' => 1005,
                'main_humidity' => 39,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 290,
                'clouds_all' => 75,
                'created_at' => '2023-08-25 10:51:34.633584+00',
            ],
            (object) [
                'id' => 100,
                'city_id' => 7,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 23.37,
                'main_feels_like' => 23.83,
                'main_pressure' => 983,
                'main_humidity' => 79,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 80,
                'clouds_all' => 40,
                'created_at' => '2023-08-25 10:51:34.878515+00',
            ],
            (object) [
                'id' => 101,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 18.61,
                'main_feels_like' => 17.7,
                'main_pressure' => 1011,
                'main_humidity' => 45,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 40,
                'clouds_all' => 0,
                'created_at' => '2023-08-26 10:27:58.075019+00',
            ],
            (object) [
                'id' => 102,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 16.4,
                'main_feels_like' => 15.69,
                'main_pressure' => 1016,
                'main_humidity' => 61,
                'visibility' => 10000,
                'wind_speed' => 3.02,
                'wind_deg' => 206,
                'clouds_all' => 100,
                'created_at' => '2023-08-26 10:27:58.405166+00',
            ],
            (object) [
                'id' => 103,
                'city_id' => 6,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 13.83,
                'main_feels_like' => 13.41,
                'main_pressure' => 1006,
                'main_humidity' => 82,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 40,
                'clouds_all' => 75,
                'created_at' => '2023-08-26 10:27:58.623609+00',
            ],
            (object) [
                'id' => 104,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 18.96,
                'main_feels_like' => 18.24,
                'main_pressure' => 999,
                'main_humidity' => 51,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 70,
                'clouds_all' => 0,
                'created_at' => '2023-08-26 10:27:58.83588+00',
            ],
            (object) [
                'id' => 105,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 20.61,
                'main_feels_like' => 20.4,
                'main_pressure' => 1006,
                'main_humidity' => 64,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 30,
                'clouds_all' => 75,
                'created_at' => '2023-08-27 12:42:42.984393+00',
            ],
            (object) [
                'id' => 106,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 20.37,
                'main_feels_like' => 19.66,
                'main_pressure' => 1009,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 3.94,
                'wind_deg' => 341,
                'clouds_all' => 91,
                'created_at' => '2023-08-27 12:42:43.447741+00',
            ],
            (object) [
                'id' => 107,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 14.94,
                'main_feels_like' => 14.92,
                'main_pressure' => 1003,
                'main_humidity' => 93,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 20,
                'clouds_all' => 75,
                'created_at' => '2023-08-27 12:42:43.78829+00',
            ],
            (object) [
                'id' => 108,
                'city_id' => 7,
                'weather_description' => 'небольшая облачность',
                'main_temp' => 20.1,
                'main_feels_like' => 19.94,
                'main_pressure' => 993,
                'main_humidity' => 68,
                'visibility' => 10000,
                'wind_speed' => 2,
                'wind_deg' => 120,
                'clouds_all' => 20,
                'created_at' => '2023-08-27 12:42:44.032135+00',
            ],
            (object) [
                'id' => 109,
                'city_id' => 2,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 18.61,
                'main_feels_like' => 19.14,
                'main_pressure' => 1003,
                'main_humidity' => 100,
                'visibility' => 9000,
                'wind_speed' => 3,
                'wind_deg' => 170,
                'clouds_all' => 75,
                'created_at' => '2023-08-28 08:59:59.142055+00',
            ],
            (object) [
                'id' => 110,
                'city_id' => 4,
                'weather_description' => 'ясно',
                'main_temp' => 20.15,
                'main_feels_like' => 19.4,
                'main_pressure' => 1012,
                'main_humidity' => 45,
                'visibility' => 10000,
                'wind_speed' => 2.12,
                'wind_deg' => 43,
                'clouds_all' => 2,
                'created_at' => '2023-08-28 08:59:59.540467+00',
            ],
            (object) [
                'id' => 111,
                'city_id' => 6,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 19.94,
                'main_feels_like' => 19.77,
                'main_pressure' => 998,
                'main_humidity' => 68,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 190,
                'clouds_all' => 75,
                'created_at' => '2023-08-28 08:59:59.777823+00',
            ],
            (object) [
                'id' => 112,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 22.94,
                'main_feels_like' => 23.27,
                'main_pressure' => 991,
                'main_humidity' => 76,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 60,
                'clouds_all' => 0,
                'created_at' => '2023-08-28 09:00:00.067935+00',
            ],
            (object) [
                'id' => 113,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 21.61,
                'main_feels_like' => 21.29,
                'main_pressure' => 1013,
                'main_humidity' => 56,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 270,
                'clouds_all' => 75,
                'created_at' => '2023-08-29 10:35:59.602599+00',
            ],
            (object) [
                'id' => 114,
                'city_id' => 4,
                'weather_description' => 'пасмурно',
                'main_temp' => 15.92,
                'main_feels_like' => 15.47,
                'main_pressure' => 1015,
                'main_humidity' => 73,
                'visibility' => 10000,
                'wind_speed' => 2.7,
                'wind_deg' => 161,
                'clouds_all' => 100,
                'created_at' => '2023-08-29 10:36:00.14931+00',
            ],
            (object) [
                'id' => 115,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 22.72,
                'main_feels_like' => 21.96,
                'main_pressure' => 1006,
                'main_humidity' => 35,
                'visibility' => 10000,
                'wind_speed' => 7.15,
                'wind_deg' => 170,
                'clouds_all' => 75,
                'created_at' => '2023-08-29 10:36:00.459215+00',
            ],
            (object) [
                'id' => 116,
                'city_id' => 7,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 21.79,
                'main_feels_like' => 22.01,
                'main_pressure' => 999,
                'main_humidity' => 76,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 180,
                'clouds_all' => 20,
                'created_at' => '2023-08-29 10:36:00.824319+00',
            ],
            (object) [
                'id' => 117,
                'city_id' => 2,
                'weather_description' => 'ясно',
                'main_temp' => 21.61,
                'main_feels_like' => 21.29,
                'main_pressure' => 1010,
                'main_humidity' => 56,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 80,
                'clouds_all' => 0,
                'created_at' => '2023-08-30 12:30:47.185955+00',
            ],
            (object) [
                'id' => 118,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 19.79,
                'main_feels_like' => 19.03,
                'main_pressure' => 1015,
                'main_humidity' => 46,
                'visibility' => 10000,
                'wind_speed' => 0.58,
                'wind_deg' => 63,
                'clouds_all' => 60,
                'created_at' => '2023-08-30 12:30:48.105014+00',
            ],
            (object) [
                'id' => 119,
                'city_id' => 6,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 15.5,
                'main_feels_like' => 15.25,
                'main_pressure' => 1001,
                'main_humidity' => 82,
                'visibility' => 10000,
                'wind_speed' => 4.02,
                'wind_deg' => 160,
                'clouds_all' => 75,
                'created_at' => '2023-08-30 12:30:48.635614+00',
            ],
            (object) [
                'id' => 120,
                'city_id' => 7,
                'weather_description' => 'ясно',
                'main_temp' => 20.91,
                'main_feels_like' => 20.81,
                'main_pressure' => 1000,
                'main_humidity' => 67,
                'visibility' => 10000,
                'wind_speed' => 5,
                'wind_deg' => 80,
                'clouds_all' => 0,
                'created_at' => '2023-08-30 12:30:49.003051+00',
            ],
            (object) [
                'id' => 121,
                'city_id' => 2,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 20.61,
                'main_feels_like' => 20.08,
                'main_pressure' => 1012,
                'main_humidity' => 52,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 250,
                'clouds_all' => 75,
                'created_at' => '2023-09-02 10:30:40.525908+00',
            ],
            (object) [
                'id' => 122,
                'city_id' => 4,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 17.84,
                'main_feels_like' => 17.74,
                'main_pressure' => 1017,
                'main_humidity' => 79,
                'visibility' => 10000,
                'wind_speed' => 0.89,
                'wind_deg' => 276,
                'clouds_all' => 100,
                'created_at' => '2023-09-02 10:30:41.019723+00',
            ],
            (object) [
                'id' => 123,
                'city_id' => 6,
                'weather_description' => 'небольшой дождь',
                'main_temp' => 18.83,
                'main_feels_like' => 18.02,
                'main_pressure' => 1009,
                'main_humidity' => 48,
                'visibility' => 10000,
                'wind_speed' => 3.13,
                'wind_deg' => 120,
                'clouds_all' => 75,
                'created_at' => '2023-09-02 10:30:41.258035+00',
            ],
            (object) [
                'id' => 124,
                'city_id' => 7,
                'weather_description' => 'переменная облачность',
                'main_temp' => 22.34,
                'main_feels_like' => 22.14,
                'main_pressure' => 1000,
                'main_humidity' => 58,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 190,
                'clouds_all' => 40,
                'created_at' => '2023-09-02 10:30:41.616938+00',
            ],
            (object) [
                'id' => 125,
                'city_id' => 2,
                'weather_description' => 'переменная облачность',
                'main_temp' => 18.61,
                'main_feels_like' => 18.41,
                'main_pressure' => 1008,
                'main_humidity' => 72,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 70,
                'clouds_all' => 40,
                'created_at' => '2023-09-03 13:30:15.340943+00',
            ],
            (object) [
                'id' => 126,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 21.46,
                'main_feels_like' => 20.68,
                'main_pressure' => 1019,
                'main_humidity' => 39,
                'visibility' => 10000,
                'wind_speed' => 2.76,
                'wind_deg' => 331,
                'clouds_all' => 52,
                'created_at' => '2023-09-03 13:30:16.504698+00',
            ],
            (object) [
                'id' => 127,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 16.61,
                'main_feels_like' => 16.08,
                'main_pressure' => 1005,
                'main_humidity' => 67,
                'visibility' => 10000,
                'wind_speed' => 1,
                'wind_deg' => 110,
                'clouds_all' => 75,
                'created_at' => '2023-09-03 13:30:16.861109+00',
            ],
            (object) [
                'id' => 128,
                'city_id' => 7,
                'weather_description' => 'переменная облачность',
                'main_temp' => 17.04,
                'main_feels_like' => 16.73,
                'main_pressure' => 996,
                'main_humidity' => 74,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 90,
                'clouds_all' => 40,
                'created_at' => '2023-09-03 13:30:17.259896+00',
            ],
            (object) [
                'id' => 129,
                'city_id' => 2,
                'weather_description' => 'переменная облачность',
                'main_temp' => 19.61,
                'main_feels_like' => 19.3,
                'main_pressure' => 1003,
                'main_humidity' => 64,
                'visibility' => 10000,
                'wind_speed' => 4,
                'wind_deg' => 100,
                'clouds_all' => 40,
                'created_at' => '2023-09-04 08:09:02.112646+00',
            ],
            (object) [
                'id' => 130,
                'city_id' => 4,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 19.46,
                'main_feels_like' => 18.85,
                'main_pressure' => 1021,
                'main_humidity' => 53,
                'visibility' => 10000,
                'wind_speed' => 2.68,
                'wind_deg' => 321,
                'clouds_all' => 82,
                'created_at' => '2023-09-04 08:09:02.690823+00',
            ],
            (object) [
                'id' => 131,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 14.94,
                'main_feels_like' => 14.63,
                'main_pressure' => 1006,
                'main_humidity' => 82,
                'visibility' => 10000,
                'wind_speed' => 7.15,
                'wind_deg' => 20,
                'clouds_all' => 75,
                'created_at' => '2023-09-04 08:09:03.069531+00',
            ],
            (object) [
                'id' => 132,
                'city_id' => 7,
                'weather_description' => 'небольшой проливной дождь',
                'main_temp' => 18.05,
                'main_feels_like' => 18.16,
                'main_pressure' => 993,
                'main_humidity' => 86,
                'visibility' => 10000,
                'wind_speed' => 3,
                'wind_deg' => 70,
                'clouds_all' => 20,
                'created_at' => '2023-09-04 08:09:03.350986+00',
            ],
            (object) [
                'id' => 133,
                'city_id' => 2,
                'weather_description' => 'пасмурно',
                'main_temp' => 14.61,
                'main_feels_like' => 14.01,
                'main_pressure' => 1010,
                'main_humidity' => 72,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 260,
                'clouds_all' => 100,
                'created_at' => '2023-09-05 11:14:28.306007+00',
            ],
            (object) [
                'id' => 134,
                'city_id' => 4,
                'weather_description' => 'переменная облачность',
                'main_temp' => 21.95,
                'main_feels_like' => 21.09,
                'main_pressure' => 1022,
                'main_humidity' => 34,
                'visibility' => 10000,
                'wind_speed' => 2.25,
                'wind_deg' => 290,
                'clouds_all' => 25,
                'created_at' => '2023-09-05 11:14:28.713532+00',
            ],
            (object) [
                'id' => 135,
                'city_id' => 6,
                'weather_description' => 'облачно с прояснениями',
                'main_temp' => 13.83,
                'main_feels_like' => 12.78,
                'main_pressure' => 1013,
                'main_humidity' => 58,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 300,
                'clouds_all' => 75,
                'created_at' => '2023-09-05 11:14:29.039442+00',
            ],
            (object) [
                'id' => 136,
                'city_id' => 7,
                'weather_description' => 'дождь',
                'main_temp' => 16.44,
                'main_feels_like' => 16.25,
                'main_pressure' => 994,
                'main_humidity' => 81,
                'visibility' => 10000,
                'wind_speed' => 6,
                'wind_deg' => 190,
                'clouds_all' => 20,
                'created_at' => '2023-09-05 11:14:29.426467+00',
            ],
        ];
    }
}
